### ISSUE TITLE
Work Status - 21st June 2016

### ISSUE THREAD

**Issue by hitesh-nitsan** [NetConsultAG/netc_memberlist#1]
Hey @angeloprevitali 

Find out first update & latest version here:

**1. Status:** We have almost completed all features described in your requirements.

**2. Extension Package:**  We have uploaded latest extension `

**3. QA Test Case:** Find here our QA Test cases which helps you to test it in more detail. 

**4. Backend Manual:** This will help you to test quickly/easily our developed extension.

....

Please check this & give us your quick feedback at your time ;)

Have a great day!

**Comment by angeloprevitali** [comment]
Thanks for files and first impression. Looks great.

As is see there are FE layouts with <table> designs in the following FE parts

\netc_memberlist-master\Resources\Private\Templates\User\List.html
\netc_memberlist-master\Resources\Private\Templates\User\Show.html

Could you please adat them to a DIV layout please?

Concerning the final check and further feedback i will need some time (until middle of july 2016)

**Could you please REMOVE the bough files due to privacy?**
NETC_Memberlist- TestCases.xlsx
BackendManual.pdf

Thanks.

Regards,
Angelo

**Comment by hitesh-nitsan** [comment]
Hi @angeloprevitali ,

Thank you very much for your quick reply.

**1. Design in following FE parts:** If possible, can you please provide HTML code?
otherwise, it's okay. We will adapt it with Div layout. :)

**2. Need some time:** Yes sure. Please take your time for the same. No problem!

**3. Remove files:** We have removed files. 

Thanks!

**Comment by hitesh-nitsan** [comment]
Hi @angeloprevitali 

We have integrated bootstraps standard here > https://github.com/NetConsultAG/netc_memberlist/blob/master/Resources/Private/Templates/User/Show.html

Please share your feedback on functionality. Thanks!

**Comment by nitsan-technologies** [comment]
Hi @michelrossier 

We have updated all issues > https://github.com/NetConsultAG/netc_memberlist/issues

Please find our latest work/code here > https://github.com/NetConsultAG/netc_memberlist/

Looking forward to your reply here. Thank you!
